### ISSUE TITLE
Stop using raw pointers

### ISSUE THREAD

**Issue by rohanshukla94** [VoidSiddhant/RendererProject#1]
When you instantiate the object using raw pointers in the private field of the class, might as well use std::shared_ptr<>, unique_ptr<>. I know you know this, but try compiling your project using both the different scenarios and then debug the code.

**Comment by VoidSiddhant** [comment]
what should i exactly look for in the debug? I ll replace all my global and local pointer handlers with smart pointers soon

**Comment by rohanshukla94** [comment]
A simple example would be

Cat* ptr = new Cat(); 
ptr->sing(); 
delete ptr;

Instead try this

shared_ptr<Cat> ptr(new Car());
ptr->sing(); 
//like this try how efficient your code becomes
And if you want to keep the use count

void count_object(std::shared_ptr<int> co)
{
    std::cout << "co.use_count() ==" <<co.use_count() << '\n'; 
}
 I'll explain debugging thing when I reach home.

**Comment by rohanshukla94** [comment]
*void count_object(std::shared_ptr<int> Co)

**Comment by VoidSiddhant** [comment]
int* ptr = &a;
int* sptr = ptr;

does this create another data copy of 'a' or both pointers just point to '&a' ... if so then i am facing the problem of multiple raw pointers , pointing the same data , which are not getting deleted ? which one is it, need to know the flaw before i can proceed to using smart_ptr

**Comment by VoidSiddhant** [comment]
also about passing pointers to function arguments , should i prefer pointers or references

void CallbyRef(int*const  ptr);
or
void CallByRef(int& ref);

also how do the function argument pointers get deleted or freed?

**Comment by VoidSiddhant** [comment]
Found the debug info about memory leak , i think ...

D3D11 WARNING: Process is terminating. Using simple reporting. Please call ReportLiveObjects() at runtime for standard reporting. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: Live Producer at 0x0000024526ADD0F0, Refcount: 2. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x0000024526A55790, Refcount: 0. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x00000245318700B0, Refcount: 0. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x000002453187B470, Refcount: 0. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x000002453187B9E0, Refcount: 0. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x000002453187BC30, Refcount: 0. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x000002453187BE80, Refcount: 0. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x000002453187C0D0, Refcount: 0. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x000002452F86A290, Refcount: 0. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x000002453187C360, Refcount: 0. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x000002452F86BA10, Refcount: 0. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x000002452F86BCB0, Refcount: 1. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x0000024531880ED0, Refcount: 0. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x000002452F86CD10, Refcount: 0. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x000002452F86D850, Refcount: 0. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x00000245318B0D30, Refcount: 0. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x0000024531880350, Refcount: 0. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x00000245318E3100, Refcount: 0. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x00000245318E2C60, Refcount: 0. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x00000245318AFCE0, Refcount: 0. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: Live                         Object :     19 [ STATE_CREATION WARNING #0: UNKNOWN]
DXGI WARNING: Live Producer at 0x0000024526A3DD58, Refcount: 4. [ STATE_CREATION WARNING #0: ]
DXGI WARNING: 	Live Object at 0x0000024526A464D0, Refcount: 3. [ STATE_CREATION WARNING #0: ]
DXGI WARNING: Live                         Object :      1 [ STATE_CREATION WARNING #0: ]

**Comment by VoidSiddhant** [comment]
All memory leaks are related to the COM interface not getting released

**Comment by rohanshukla94** [comment]
Give me some time I want to jump into this project. After 9th April though.

**Comment by rohanshukla94** [comment]
See if you use QT 5.0 for rendering opengl you would get rid of shitty Windows "handles"
http://doc.qt.io/qt-5/qtopengl-index.html

**Comment by rohanshukla94** [comment]
Also make sure you have your assignment operators(for every class object that you export) in place before using smart pointers

**Comment by VoidSiddhant** [comment]
"See if you use QT 5.0 for rendering opengl you would get rid of shitty Windows "handles"
http://doc.qt.io/qt-5/qtopengl-index.html" 

Not using OpenGL here , working on DirectX 11

**Comment by VoidSiddhant** [comment]
DirectX sdk provides a Debug interface which revealed all the COM interfaces not getting released
Used : 

		ID3D11Debug* debugDevice;
		lp_d3dDevice->QueryInterface(__uuidof(ID3D11Debug), reinterpret_cast<void**>(&debugDevice));
		debugDevice->ReportLiveDeviceObjects(D3D11_RLDO_DETAIL); 

Output :

D3D11 WARNING: Live ID3D11Device at 0x0000021F8D4B6440, Name: Graphic, Refcount: 16 [ STATE_CREATION WARNING #441: LIVE_DEVICE]
D3D11 WARNING: 	Live ID3D11Context at 0x0000021F8D467040, Name: Graphic, Refcount: 1, IntRef: 1 [ STATE_CREATION WARNING #2097226: LIVE_CONTEXT]
D3D11 WARNING: 	Live ID3DDeviceContextState at 0x0000021F982D00B0, Refcount: 0, IntRef: 1 [ STATE_CREATION WARNING #3145742: LIVE_DEVICECONTEXTSTATE]
D3D11 WARNING: 	Live ID3D11BlendState at 0x0000021F962C9440, Refcount: 0, IntRef: 1 [ STATE_CREATION WARNING #435: LIVE_BLENDSTATE]
D3D11 WARNING: 	Live ID3D11DepthStencilState at 0x0000021F962C99B0, Refcount: 0, IntRef: 1 [ STATE_CREATION WARNING #436: LIVE_DEPTHSTENCILSTATE]
D3D11 WARNING: 	Live ID3D11RasterizerState at 0x0000021F962C9C00, Refcount: 0, IntRef: 1 [ STATE_CREATION WARNING #437: LIVE_RASTERIZERSTATE]
D3D11 WARNING: 	Live ID3D11Sampler at 0x0000021F982DB470, Refcount: 0, IntRef: 1 [ STATE_CREATION WARNING #434: LIVE_SAMPLER]
D3D11 WARNING: 	Live ID3D11Query at 0x0000021F982DB6C0, Refcount: 0, IntRef: 1 [ STATE_CREATION WARNING #438: LIVE_QUERY]
D3D11 WARNING: 	Live IDXGISwapChain at 0x0000021F982DB920, Refcount: 1 [ STATE_CREATION WARNING #442: LIVE_SWAPCHAIN]
D3D11 WARNING: 	Live ID3D11Texture2D at 0x0000021F982DC680, Refcount: 0, IntRef: 1 [ STATE_CREATION WARNING #425: LIVE_TEXTURE2D]
D3D11 WARNING: 	Live ID3D11RenderTargetView at 0x0000021F962CAC70, Refcount: 1, IntRef: 0 [ STATE_CREATION WARNING #428: LIVE_RENDERTARGETVIEW]
D3D11 WARNING: 	Live ID3D11Texture2D at 0x0000021F962CAF10, Refcount: 1, IntRef: 1 [ STATE_CREATION WARNING #425: LIVE_TEXTURE2D]
D3D11 WARNING: 	Live ID3D11DepthStencilView at 0x0000021F982E0DF0, Refcount: 1, IntRef: 0 [ STATE_CREATION WARNING #429: LIVE_DEPTHSTENCILVIEW]
D3D11 WARNING: 	Live ID3D11ClassLinkage at 0x0000021F962CDF10, Name: x64/Debug/Color.cso, Refcount: 1, IntRef: 0 [ STATE_CREATION WARNING #2097294: LIVE_CLASSLINKAGE]
D3D11 WARNING: 	Live ID3D11Buffer at 0x0000021F962CE410, Name: x64/Debug/Color.cso, Refcount: 1, IntRef: 0 [ STATE_CREATION WARNING #423: LIVE_BUFFER]
D3D11 WARNING: 	Live ID3D11VertexShader at 0x0000021F982F1DB0, Name: x64/Debug/Color.cso, Refcount: 1, IntRef: 0 [ STATE_CREATION WARNING #430: LIVE_VERTEXSHADER]
D3D11 WARNING: 	Live ID3D11PixelShader at 0x0000021F9830EAE0, Name: x64/Debug/Color.cso, Refcount: 1, IntRef: 0 [ STATE_CREATION WARNING #432: LIVE_PIXELSHADER]
D3D11 WARNING: 	Live ID3D11InputLayout at 0x0000021F982DE170, Refcount: 1, IntRef: 0 [ STATE_CREATION WARNING #433: LIVE_INPUTLAYOUT]
D3D11 WARNING: 	Live ID3D11Buffer at 0x0000021F98305A20, Refcount: 1, IntRef: 0 [ STATE_CREATION WARNING #423: LIVE_BUFFER]
D3D11 WARNING: 	Live ID3D11Buffer at 0x0000021F98306540, Refcount: 1, IntRef: 0 [ STATE_CREATION WARNING #423: LIVE_BUFFER]
D3D11 WARNING: 	Live ID3D11Texture2D at 0x0000021F98305460, Refcount: 0, IntRef: 1 [ STATE_CREATION WARNING #425: LIVE_TEXTURE2D]
D3D11 INFO: Destroy ID3D11ClassLinkage: Name="x64/Debug/Color.cso", Addr=0x0000021F962CDF10 [ STATE_CREATION INFO #2097295: DESTROY_CLASSLINKAGE]
