### ISSUE TITLE
Timer

### ISSUE THREAD

**Issue by rohanshukla94** [VoidSiddhant/RendererProject#3]
https://github.com/VoidSiddhant/RendererProject/blob/b2c0fe359d3f7d8fe942f2b52b0d02054bacd9b3/Include/Timer.h#L9

Try using chrono c++11 library
https://github.com/voidrohan/moderncpp/blob/master/libfeatures/chrono.h

**Comment by VoidSiddhant** [comment]
this is working perfectly for now , i dont see any downside to current implementation?
